### ISSUE TITLE
Switch Jest test files to TypeScript

### ISSUE THREAD

**Issue by ProchaLu** [upleveled/next-js-example-spring-2022#10]
In our `next-js-example-spring-2022` file, we have the Jest test files in JavaScript, and we want to switch to TypeScript. 
We are setting up Jest with the Rust Compiler. 

https://nextjs.org/docs/testing#setting-up-jest-with-the-rust-compiler

Switching to TypeScript works out of the box with the Rust Compiler, so we don't have to add any package. 

1. Rename the Jest test files to `.ts` 

<img width="277" alt="Screenshot 2022-08-03 at 11 57 47" src="https://user-images.githubusercontent.com/80746311/182581001-723470dc-9146-41fe-8794-cfc48e1045d2.png">

2. Change the `cookies.test.ts` file because of TypeScript errors. 

	In the TypeScript lecture we add a type to the `stringifyCookieValue()` function. The value before was not assignable to							 	 	this type, and we have to change test data to conform to the type. 

```diff
test('stringify a cookie value', () => {
-  expect(stringifyCookieValue({ 1: 10, 2: 15 })).toBe('{"1":10,"2":15}');
+  expect(stringifyCookieValue([{ id: '1', eatCounter: 2 }])).toBe(
+    '[{"id":"1","eatCounter":2}]',
+  );
});
```

3. Change the `math.test.ts` file because, in this test, we want to throw an error if the arguments are not numbers, but TypeScript throws an error before running the test.

	There are different solutions to this issue. The most common solutions are using `// @ts-ignore` or `// @ts-expect-error`.

	The TypeScript docs recommend using `// @ts-expect-error` because we are writing test code where we want the type system to error on an operation.

	https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#ts-ignore-or-ts-expect-error:~:text=Pick%20ts%2Dexpect,on%20an%20operation

```diff
test('throws an error if arguments are not numbers', () => {
+ // @ts-expect-error testing incorrect argument type
  expect(() => sum(1, '2')).toThrow('Pass only numbers!');
+ // @ts-expect-error testing incorrect argument type
  expect(() => sum(2, true)).toThrow('Pass only numbers!');
});
```

**Comment by karlhorky** [comment]
Good proposal! Seems like these changes are minimal, so you could apply them to the existing Spring example too? Then we can close this one.

**Comment by ProchaLu** [comment]
I switched the Jest tests to TypeScript and added the changes from the proposal.
Commit: [7812133](https://github.com/upleveled/next-js-example-spring-2022/commit/7812133908d8483cda935056c2ac3bdddcf38cb0)
