### ISSUE TITLE
Use Postgres.js internal camelcase options

### ISSUE THREAD

**Issue by Eprince-hub** [upleveled/next-js-example-spring-2022#8]
Postgres.js provides a way to normalize database data from `snake_case` to `camelCase` 
docs here: https://github.com/porsager/postgres#data-transformation

We should delete camelcase-keys and use Postgres.js internal camelcase options
Code example
```bash
    globalThis.postgresSqlClient = postgres({
      transform: {
        column: {
          from: postgres.toCamel,
        },
      },
    });
```

**Comment by karlhorky** [comment]
Sounds like a good idea! Let's do it for the next example.
