### ISSUE TITLE
Switch to separate files in a database folder

### ISSUE THREAD

**Issue by Eprince-hub** [upleveled/next-js-example-spring-2022#9]
Change the database file structure from `util/database.ts` to more organized way using the `database` folder, like the example below
`security-vulnerability-examples-next-js-postgres/database/connect.ts`
Detailed example
https://github.com/upleveled/security-vulnerability-examples-next-js-postgres/tree/main/database

**Comment by karlhorky** [comment]
Sounds like a good idea! Let's do it for the next example.
